import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/components/context/UserContext";
import { ProjectProvider } from "@/components/context/ProjectContext";
import { TaskProvider } from "@/components/context/TaskContext";
import { UsersProvider } from "@/components/context/UsersContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ProjectProvider>
            <UsersProvider>
              <TaskProvider>{children}</TaskProvider>
            </UsersProvider>
          </ProjectProvider>
        </UserProvider>
      </body>
    </html>
  );
}
